"""A/B harness: run the baseline against one-change-at-a-time variants.

    python3 ab_test.py --data ./bars          # real daily bars, one CSV per symbol
    python3 ab_test.py --synthetic            # mechanics smoke run only

Each arm changes exactly one thing against the baseline, so a difference in the
table is attributable. Arms that combine changes are listed last and only make
sense once the single changes have been read.
"""

from __future__ import annotations

import argparse
import sys

import pandas as pd

import data as data_mod
import metrics
from backtester import run_config
from strategy import StrategyConfig

SYNTHETIC_WARNING = """
!!  These results come from SYNTHETIC bars generated by a random-number seed.
!!  They demonstrate that the engine runs and that each switch changes behaviour.
!!  They are NOT evidence of an edge and must never be quoted as performance.
!!  Re-run with --data pointing at real daily bars for a result that means anything.
"""


def build_arms(baseline: StrategyConfig) -> list[StrategyConfig]:
    """The baseline plus one arm per idea, each isolating a single change."""
    return [
        baseline,
        # --- extracted from the gap-and-go script ---------------------------
        baseline.variant("gap_required_2.5%", gap_mode="required", min_gap_pct=0.025),
        baseline.variant("gap_required_1.5%", gap_mode="required", min_gap_pct=0.015),
        baseline.variant("gap_ranked_first", gap_mode="bonus"),
        baseline.variant("regime_spy+qqq_strict", regime_mode="dual_index_strict"),
        # --- exit management -------------------------------------------------
        baseline.variant("scale_out_2R", exit_mode="scale_out"),
        # --- deliberate downgrades, kept so the comparison is honest ---------
        baseline.variant("fixed_2pct_stop", stop_mode="fixed_pct", fixed_stop_pct=0.02),
        baseline.variant("risk_0.25pct", risk_pct=0.0025),
        # --- combinations ----------------------------------------------------
        baseline.variant("gap+scale_out", gap_mode="required", exit_mode="scale_out"),
        baseline.variant("gap+strict_regime+scale_out", gap_mode="required",
                         regime_mode="dual_index_strict", exit_mode="scale_out"),
    ]


def run_matrix(arms, universe, benchmarks, **engine_kwargs):
    rows, curves = [], {}
    for cfg in arms:
        perf, curve, blotter = run_config(cfg, universe, benchmarks, **engine_kwargs)
        row = {"variant": cfg.name, **perf.as_dict()}
        rows.append(row)
        curves[cfg.name] = curve
        print(f"  ran {cfg.name:<28} {perf.trades:>5} trades  "
              f"win {perf.win_rate:6.1%}  ret {perf.total_return:8.1%}  "
              f"maxDD {perf.max_drawdown:6.1%}", flush=True)
    return pd.DataFrame(rows).set_index("variant"), curves


def format_table(table: pd.DataFrame) -> str:
    view = table.copy()
    for col in ("win_rate", "total_return", "cagr", "max_drawdown", "exposure"):
        view[col] = (view[col] * 100).round(1)
    for col in ("profit_factor", "expectancy_r", "avg_win_r", "avg_loss_r",
                "largest_win_r", "sharpe"):
        view[col] = view[col].round(2)
    view = view.rename(columns={
        "win_rate": "win%", "total_return": "ret%", "cagr": "cagr%",
        "max_drawdown": "maxDD%", "profit_factor": "PF", "expectancy_r": "exp_R",
        "avg_win_r": "avgW_R", "avg_loss_r": "avgL_R", "largest_win_r": "maxW_R",
        "exposure": "expo%",
    })
    ordered = ["trades", "win%", "ret%", "cagr%", "maxDD%", "PF", "exp_R",
               "avgW_R", "avgL_R", "maxW_R", "sharpe", "expo%"]
    return view[ordered].to_string()


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data", help="directory of <SYMBOL>.csv daily bars")
    parser.add_argument("--synthetic", action="store_true",
                        help="run on generated bars (mechanics check only)")
    parser.add_argument("--symbols", type=int, default=60, help="synthetic universe size")
    parser.add_argument("--days", type=int, default=1500, help="synthetic history length")
    parser.add_argument("--equity", type=float, default=100_000.0)
    parser.add_argument("--cost-bps", type=float, default=5.0)
    parser.add_argument("--out", help="write the results table to this CSV")
    args = parser.parse_args(argv)

    if not args.data and not args.synthetic:
        parser.error("pass --data <dir> for a real backtest, or --synthetic for a smoke run")

    if args.data:
        frames = data_mod.load_csv_dir(args.data)
        benchmarks = {t: frames.pop(t) for t in ("SPY", "QQQ") if t in frames}
        if "SPY" not in benchmarks:
            print("error: SPY.csv is required in the data directory (regime gate)", file=sys.stderr)
            return 2
        if "QQQ" not in benchmarks:
            print("note: no QQQ.csv - the strict dual-index regime arm cannot run", file=sys.stderr)
        universe = frames
        print(f"loaded {len(universe)} symbols, "
              f"{benchmarks['SPY'].index[0].date()} to {benchmarks['SPY'].index[-1].date()}")
    else:
        print(SYNTHETIC_WARNING)
        universe, benchmarks = data_mod.synthetic_universe(
            n_symbols=args.symbols, days=args.days)

    baseline = StrategyConfig(name="baseline_fixed_4R")
    arms = build_arms(baseline)
    if "QQQ" not in benchmarks:
        arms = [a for a in arms if a.regime_mode != "dual_index_strict"]

    print(f"\nrunning {len(arms)} arms...")
    table, curves = run_matrix(arms, universe, benchmarks,
                               starting_equity=args.equity, cost_bps=args.cost_bps)

    print("\n" + "=" * 110)
    print(format_table(table))
    print("=" * 110)

    print("\nper-calendar-year returns (%)")
    yearly = pd.DataFrame({name: metrics.yearly_returns(curve) * 100
                           for name, curve in curves.items()}).round(1)
    print(yearly.to_string())

    if args.synthetic:
        print(SYNTHETIC_WARNING)
    if args.out:
        table.to_csv(args.out)
        print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
